### ISSUE TITLE
Submitting recordings are failing with a 401 code

### ISSUE THREAD

**Issue by abdelrahman-elkady** [Tarteel-io/tarteel-frontend#102]
### Steps to reproduce
1. Go to tarteel.io/contribute
2. Submit a recording for a verse or more
3. All requests trying to hit `POST https://api.tarteel.io/v1/recordings/` are failing with status code `401`

Please check the screenshots below:

![Screenshot from 2019-10-01 18-38-40](https://user-images.githubusercontent.com/10640699/65982359-75348f80-e47b-11e9-8719-97f7271dc1a0.png)

![image](https://user-images.githubusercontent.com/10640699/65982304-51714980-e47b-11e9-8641-f403ea7b59e3.png)

**Comment by piraka9011** [comment]
The fix is currently being reviewed in #113. Will close this issue once it is deployed to production.

JAK for letting us know.

**Comment by piraka9011** [comment]
@abdelrahman-elkady This fix has been deployed https://tarteel.io/contribute

**Comment by abdelrahman-elkady** [comment]
@piraka9011 JAK, great job guys, keep on the amazing work :))
