### ISSUE TITLE
Invalid text for aya evaluation

### ISSUE THREAD

**Issue by Amr1977** [Tarteel-io/tarteel-frontend#3]
Salam :)

Jazakom Allah Khiran you for the magnificent work :)

While evaluating recitations, a valid audio was heared but invalid text is shown as in attached image. 

![2019-02-17_0701](https://user-images.githubusercontent.com/3415198/52908723-07d54500-3284-11e9-8f49-329a30c45e65.png)

**Comment by tifa2UP** [comment]
Salam Amr, this happens while the font is loading. Our fonts currently have a big size so we're working on reducing it. Closing for now but feel free to reopen if the problem persists.

Thanks @Amr1977!
