### ISSUE TITLE
Refactor the settings menu to use a generic dropdown component

### ISSUE THREAD

**Issue by Ananasship** [Tarteel-io/tarteel-frontend#47]
We want to refactor the current settings menu (pictured below) to use a generic dropdown component: 

![image](https://user-images.githubusercontent.com/50060474/60154904-a1b27e80-979d-11e9-90cc-4ef241b020b9.png)

The current implementation is very tightly coupled to the settings menu. Ideally, the new component will take render any type of children, be extensible, and easy to use. We plan on using it an upcoming page like this: 

![Kiosk page settings menu Copy](https://user-images.githubusercontent.com/50060474/60155004-dc1c1b80-979d-11e9-8b06-26a929124ced.png)

We want you to use your best judgment and demonstrate clean code quality. But feel free to message any of the Tarteel team members if you have questions.

You will need to: 

- Create a new `Dropdown` component, feel free to reuse the current implementation / css as a start.
- Make the settings menu use the new component instead of hardcoding the implementation
- Make sure that the behavior is unchanged with the refactoring. 
- Once you're done, you can create a PR with your changes

**Comment by alzalabany** [comment]
i'm on it,
https://codesandbox.io/s/github/alzalabany/generic-react-dropdown
i will develope it in separate and merge it later
