### ISSUE TITLE
Repository names, organisation name, top-level repo and empty repository

### ISSUE THREAD

**Issue by mbana** [Tarteel-io/tarteel-frontend#76]
No idea where to raise this but these are small (or large depending on your stance) points.

1. Can you please lowercase all the repository names

```sh
$ git clone git@github.com:Tarteel-io/tarteel-frontend.git
$ git clone git@github.com:Tarteel-io/Tarteel-ML.git
$ git clone git@github.com:Tarteel-io/tarteel-api.git
$ git clone git@github.com:Tarteel-io/tarteel-mobile.git
$ git clone git@github.com:Tarteel-io/Tarteel-voice.git
$ git clone git@github.com:Tarteel-io/tarteel-app.git
$ git clone git@github.com:Tarteel-io/tarteel-assets.git
Cloning into 'tarteel-assets'...
warning: You appear to have cloned an empty repository.
$ git clone git@github.com:Tarteel-io/tarteel-dataset-labeler.git
$ git clone git@github.com:Tarteel-io/tarteel-docs.git
```

2. Can you please lowercase the organisation name, i.e., https://github.com/tarteel-io.
3. Would be nice to have a top-level repo, such as https://github.com/tarteel-io/tarteel, that contains useful information and where people can also raise issues.
4. This repository is empty: https://github.com/Tarteel-io/tarteel-assets:

```sh
git clone git@github.com:Tarteel-io/tarteel-assets.git
Cloning into 'tarteel-assets'...
warning: You appear to have cloned an empty repository.
```

**Comment by piraka9011** [comment]
We can't change the org name but we have renamed the repos for consistency.
A meta-repo (top level repo) is something we have in mind for the future iA.
Tarteel assets will be used in the future iA :)
